from tkinter import *
from tkinter import ttk

root = Tk()

ttk.Label(root, text='Naam formulier:').grid(row=0, column=1, pady=5)
ttk.Label(root, text='Datum:').grid(row=0, column=3, pady=5)

naam = ttk.Entry(root, width=30).grid(row=1, column=1)
datum = ttk.Entry(root, width=20, state='disabled').grid(row=1, column=3)

_save = ttk.Button(root, text='Save', command=lambda: print('Save Btn')).grid(row=0, column=5)
_open = ttk.Button(root, text='Open', command=lambda: print('Open Btn')).grid(row=0, column=6)

type1_label = ttk.Label(text='Type 1:').grid(row=2, column=1)
type2_label = ttk.Label(text='Type 2:').grid(row=2, column=3)
type3_label = ttk.Label(text='Type 3:').grid(row=2, column=5)

type1 = ttk.Entry(root, width=30).grid(row=3, column=1, rowspan=2, padx=10)
type2 = ttk.Entry(root, width=30).grid(row=3, column=3, rowspan=2, padx=10)
type3 = ttk.Entry(root, width=30).grid(row=3, column=5, rowspan=1, padx=10)

frame1 = ttk.Frame(root)
frame1.grid(row=5, column=0)


frame_type1 = ttk.Frame(root)
frame_type1.grid(row=5, column=1)

frame_type2 = ttk.Frame(root)
frame_type2.grid(row=5, column=3)

frame_type3 = ttk.Frame(root)
frame_type3.grid(row=5, column=5)


cb1 = Checkbutton(frame1, text='AP', variable='AP')
cb1.pack(anchor='w')
cb2 = Checkbutton(frame1, text='BL', variable='BL')
cb2.pack(anchor='w')
cb3 = Checkbutton(frame1, text='DD', variable='DD')
cb3.pack(anchor='w')
cb4 = Checkbutton(frame1, text='ID', variable='ID')
cb4.pack(anchor='w')
cb5 = Checkbutton(frame1, text='KD', variable='KD')
cb5.pack(anchor='w')
cb6 = Checkbutton(frame1, text='KZ', variable='KZ')
cb6.pack(anchor='w')
cb7 = Checkbutton(frame1, text='ME', variable='ME')
cb7.pack(anchor='w')
cb8 = Checkbutton(frame1, text='MP', variable='MP')
cb8.pack(anchor='w')
cb9 = Checkbutton(frame1, text='PH', variable='PH')
cb9.pack(anchor='w')
cb10 = Checkbutton(frame1, text='PL', variable='PL')
cb10.pack(anchor='w')
cb11 = Checkbutton(frame1, text='RS', variable='RS')
cb11.pack(anchor='w')
cb12 = Checkbutton(frame1, text='WH', variable='WH')
cb12.pack(anchor='w')
cb13 = Checkbutton(frame1, text='WN', variable='WN')
cb13.pack(anchor='w')
cb14 = Checkbutton(frame1, text='WD', variable='WD')
cb14.pack(anchor='w')
cb15 = Checkbutton(frame1, text='WZ', variable='WZ')
cb15.pack(anchor='w')


cbt1_1 = Checkbutton(frame_type1, text=type1, variable='type 1_1')
cbt1_1.pack(anchor='w')
cbt1_2 = Checkbutton(frame_type1, text=type1, variable='type 1_2')
cbt1_2.pack(anchor='w')
cbt1_3 = Checkbutton(frame_type1, text=type1, variable='type 1_3')
cbt1_3.pack(anchor='w')
cbt1_4 = Checkbutton(frame_type1, text=type1, variable='type 1_4')
cbt1_4.pack(anchor='w')
cbt1_5 = Checkbutton(frame_type1, text=type1, variable='type 1_5')
cbt1_5.pack(anchor='w')
cbt1_6 = Checkbutton(frame_type1, text=type1, variable='type 1_6')
cbt1_6.pack(anchor='w')
cbt1_7 = Checkbutton(frame_type1, text=type1, variable='type 1_7')
cbt1_7.pack(anchor='w')
cbt1_8 = Checkbutton(frame_type1, text=type1, variable='type 1_8')
cbt1_8.pack(anchor='w')
cbt1_9 = Checkbutton(frame_type1, text=type1, variable='type 1_9')
cbt1_9.pack(anchor='w')
cbt1_10 = Checkbutton(frame_type1, text=type1, variable='type 1_10')
cbt1_10.pack(anchor='w')
cbt1_11 = Checkbutton(frame_type1, text=type1, variable='type 1_11')
cbt1_11.pack(anchor='w')
cbt1_12 = Checkbutton(frame_type1, text=type1, variable='type 1_12')
cbt1_12.pack(anchor='w')
cbt1_13 = Checkbutton(frame_type1, text=type1, variable='type 1_13')
cbt1_13.pack(anchor='w')
cbt1_14 = Checkbutton(frame_type1, text=type1, variable='type 1_14')
cbt1_14.pack(anchor='w')
cbt1_15 = Checkbutton(frame_type1, text=type1, variable='type 1_15')
cbt1_15.pack(anchor='w')


cbt2_1 = Checkbutton(frame_type2, text='type ...', variable='type 2_1')
cbt2_1.pack(anchor='w')
cbt2_2 = Checkbutton(frame_type2, text='type ...', variable='type 2_2')
cbt2_2.pack(anchor='w')
cbt2_3 = Checkbutton(frame_type2, text='type ...', variable='type 2_3')
cbt2_3.pack(anchor='w')
cbt2_4 = Checkbutton(frame_type2, text='type ...', variable='type 2_4')
cbt2_4.pack(anchor='w')
cbt2_5 = Checkbutton(frame_type2, text='type ...', variable='type 2_5')
cbt2_5.pack(anchor='w')
cbt2_6 = Checkbutton(frame_type2, text='type ...', variable='type 2_6')
cbt2_6.pack(anchor='w')
cbt2_7 = Checkbutton(frame_type2, text='type ...', variable='type 2_7')
cbt2_7.pack(anchor='w')
cbt2_8 = Checkbutton(frame_type2, text='type ...', variable='type 2_8')
cbt2_8.pack(anchor='w')
cbt2_9 = Checkbutton(frame_type2, text='type ...', variable='type 2_9')
cbt2_9.pack(anchor='w')
cbt2_10 = Checkbutton(frame_type2, text='type ...', variable='type 2_10')
cbt2_10.pack(anchor='w')
cbt2_11 = Checkbutton(frame_type2, text='type ...', variable='type 2_11')
cbt2_11.pack(anchor='w')
cbt2_12 = Checkbutton(frame_type2, text='type ...', variable='type 2_12')
cbt2_12.pack(anchor='w')
cbt2_13 = Checkbutton(frame_type2, text='type ...', variable='type 2_13')
cbt2_13.pack(anchor='w')
cbt2_14 = Checkbutton(frame_type2, text='type ...', variable='type 2_14')
cbt2_14.pack(anchor='w')
cbt2_15 = Checkbutton(frame_type2, text='type ...', variable='type 2_15')
cbt2_15.pack(anchor='w')


cbt3_1 = Checkbutton(frame_type3, text='type ...', variable='type 3_1')
cbt3_1.pack(anchor='w')
cbt3_2 = Checkbutton(frame_type3, text='type ...', variable='type 3_2')
cbt3_2.pack(anchor='w')
cbt3_3 = Checkbutton(frame_type3, text='type ...', variable='type 3_3')
cbt3_3.pack(anchor='w')
cbt3_4 = Checkbutton(frame_type3, text='type ...', variable='type 3_4')
cbt3_4.pack(anchor='w')
cbt3_5 = Checkbutton(frame_type3, text='type ...', variable='type 3_5')
cbt3_5.pack(anchor='w')
cbt3_6 = Checkbutton(frame_type3, text='type ...', variable='type 3_6')
cbt3_6.pack(anchor='w')
cbt3_7 = Checkbutton(frame_type3, text='type ...', variable='type 3_7')
cbt3_7.pack(anchor='w')
cbt3_8 = Checkbutton(frame_type3, text='type ...', variable='type 3_8')
cbt3_8.pack(anchor='w')
cbt3_9 = Checkbutton(frame_type3, text='type ...', variable='type 3_9')
cbt3_9.pack(anchor='w')
cbt3_10 = Checkbutton(frame_type3, text='type ...', variable='type 3_10')
cbt3_10.pack(anchor='w')
cbt3_11 = Checkbutton(frame_type3, text='type ...', variable='type 3_11')
cbt3_11.pack(anchor='w')
cbt3_12 = Checkbutton(frame_type3, text='type ...', variable='type 3_12')
cbt3_12.pack(anchor='w')
cbt3_13 = Checkbutton(frame_type3, text='type ...', variable='type 3_13')
cbt3_13.pack(anchor='w')
cbt3_14 = Checkbutton(frame_type3, text='type ...', variable='type 3_14')
cbt3_14.pack(anchor='w')
cbt3_15 = Checkbutton(frame_type3, text='type ...', variable='type 3_15')
cbt3_15.pack(anchor='w')


root.mainloop()
