#! /usr/bin/env python3.5
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    May 08, 2017 12:51:15 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

# import unknown_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    # unknown_support.set_Tk_var()
    top = New_Toplevel_1 (root)
    # unknown_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    # unknown_support.set_Tk_var()
    top = New_Toplevel_1 (w)
    # unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+650+150")
        top.title("New Toplevel 1")
        top.configure(background="#d9d9d9")
        top.configure(highlightcolor="#646464646464")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.43, rely=0.62, height=24, width=47)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=0.61, relwidth=0.64)
        self.Canvas1.configure(background="#ffffffffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(cursor="target")
        self.Canvas1.configure(highlightbackground="#f0f0f0f0f0f0")
        self.Canvas1.configure(insertbackground="#000000")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=378)

        self.Checkbutton1 = Checkbutton(top)
        self.Checkbutton1.place(relx=0.67, rely=0.02, relheight=0.06
                , relwidth=0.1)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Check''')
        # self.Checkbutton1.configure(variable=unknown_support.che42)






if __name__ == '__main__':
    vp_start_gui()


